
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
//import org.springframework.boot.SpringApplication;
import org.springframework.context.annotation.Bean;
//import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

@SpringBootApplication
public class App {
	
	private static final Logger log = LoggerFactory.getLogger(App.class);

	
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        SpringApplication.run(App.class);
    }
    
    @Bean
    public CommandLineRunner demo(BkMenuRepository repository) {
		return (args) -> {	
			repository.findAll();
			log.error("this is CommandLineRunner");
		};
	}
}
